name: Playwright Tests with Tracing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright
        pip install python-dotenv
        playwright install

    - name: Access passwords
      run: echo "${{ secrets.ENVIRONMENT_SECRETS }}"

    - name: Create traces directory
      run: mkdir -p traces/

    # Enable tracing by setting the environment variable
    - name: Run Playwright tests with tracing
      run:
        # pytest tests/ --html=report.html --self-contained-html
        # pytest tests/
        export PYTHONPATH=$(pwd) && pytest 3c_Manager/tests/login_pg_reset_password.py
      env:
        PLAYWRIGHT_TRACE_DIR: traces/  # This is where the traces will be stored

    # Upload the traces for later inspection
    - name: Upload Playwright trace artifacts
      uses: actions/upload-artifact@v3
      with:
        name: playwright-traces
        path: traces/  # Path to the trace files